import type { Metadata } from "next";
import { Providers } from "~/providers/providers";
import { vazirmatn } from "./fonts";
import "~/styles/globals.css";

export const metadata: Metadata = {
	title: "stream-tube",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			suppressHydrationWarning
			lang="fa"
			dir="rtl"
			className={`${vazirmatn.variable}`}
		>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
